version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: skitiswaif123
      MYSQL_DATABASE: inventario_db
      MYSQL_USER: user
      MYSQL_PASSWORD: skitiswaif123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3307:3306' 

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: skitiswaif123
      MYSQL_DATABASE: inventario_db
      MYSQL_HOST: mysql
      PORT: 3000
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    command: >
      sh -c "
      npm install &&
      npx sequelize-cli db:migrate &&
      npm start
      "  

volumes:
  mysql_data:
    driver: local
